version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/db
    environment:
      - SQLITE_DATABASE=development.sqlite3

